name: "Upload to Yandex S3 Object Storage"
description: "GH action for uploading files to Yandex S3 Object Storage"
author: "Pavel Strashnov and Ivan E :)"
inputs:
    accessKeyId:
        description: "Service account access key ID"
        default: ""
        required: true
    secretAccessKey:
        description: "Service account secret access key"
        default: ""
        required: true
    bucket:
        description: "Bucket name"
        default: ""
        required: true
    localPath:
        description: "Path to file or folder to upload"
        default: "./"
        required: true
    remotePath:
        description: "Path in Yandex S3 to upload files to"
        default: "./"
        required: true
    clearBucket:
        description: "Clear ALL storage"
        default: 'false'
        required: false

runs:
    using: "node16"
    main: "dist/index.js"
branding:
    icon: "upload-cloud"
    color: "blue"